steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-docker.pkg.dev/cloud-run-demo-388010/my-artifact-repo/cloudrun:latest",
        ".",
        "--build-arg",
        "API_PORT=8080"
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-docker.pkg.dev/cloud-run-demo-388010/my-artifact-repo/cloudrun:latest"
      ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      "run", 
      "deploy",
      "cloudrun",
      "--image",
      "us-docker.pkg.dev/cloud-run-demo-388010/my-artifact-repo/cloudrun:latest",
      "--region",
      "asia-south1",
      "--platform",
      "managed",
    ]
